### ISSUE TITLE
tls for i386 is not correct

### ISSUE THREAD

**Issue by bruce30262** [scwuaptx/Pwngdb#1]
Hi,  Bruce here :)
Spot a weird implementation in your debugger
Please correct me if I have any misunderstanding !  
  
Although there's been a lot less i386 binary in the CTF pwning challenge now
I think I'll still point out that the `gettls` function for the i386 binary isn't giving the correct address
In fact I'm quite surprise that you are using `libc's base address - 0x300` as the `tcbhead_t`'s base address , where did you get that information ? Can you provide the reference?  
  
BTW , I've also implement getting the tls address in my own debugger, too (by modifying gdb-peda's source code), here the [link](https://github.com/bruce30262/peda/blob/master/peda.py) ( at line `4494`, function `tls_i386`)  
According to [this link](https://fossies.org/dox/glibc-2.23/i386_2nptl_2tls_8h_source.html#l00047), `sysinfo` will be stored as the 5th member of a `tcbheader_t`'s structure, which is at `tls base address + 0x10`. So here's how I implement:  
* Find the address of the `__kernel_vsyscall` ( = `sysinfo` ) by using `info functions`  
* Find the address that stores the `sysinfo`  
* The tls base address = `address that stores the sysinfo - 0x10`  
  
Here's the difference between your `gettls` function and mine (test in Ubuntu Linux 14.04 32 bit):  
yours:  
```
gdb-peda$ info proc
process 3844
cmdline = './Desktop/starbound_patch'
cwd = '/home/bruce30262'
exe = '/home/bruce30262/Desktop/starbound_patch'
gdb-peda$ tls
tls : 0xb743a700
gdb-peda$ canary
canary : 0x9691973  <-- no null byte
gdb-peda$ 
```  
mine:  
```
gdb-peda$ info proc
process 3844
cmdline = './Desktop/starbound_patch'
cwd = '/home/bruce30262'
exe = '/home/bruce30262/Desktop/starbound_patch'
gdb-peda$ tls
setting $tls = 0xb7434700
setting $canary = 0x87354b00
0xb7434680:	0x00000000	0x00000000	0x00000000	0x00000000
0xb7434690:	0x00000000	0x00000000	0x00000000	0x00000000
0xb74346a0:	0x00000000	0x00000000	0x00000000	0x00000000
0xb74346b0:	0x00000000	0xb75e68a0	0xb75e8fc0	0x00000000
0xb74346c0:	0xb75871a0	0xb7586ba0	0xb7587aa0	0x00000000
0xb74346d0:	0x00000000	0x00000000	0xb75e6420	0x00000000
0xb74346e0:	0x00000000	0x00000000	0x00000000	0x00000000
0xb74346f0:	0x00000000	0x00000000	0x00000000	0x00000000
0xb7434700:	0xb7434700	0xb7434bc8	0xb7434700	0x00000000
0xb7434710:	0xb77b3414	0x87354b00	0x18ff5a26	0x00000000
0xb7434720:	0x00000000	0x00000000	0x00000000	0x00000000
0xb7434730:	0x00000000	0x00000000	0x00000000	0x00000000
0xb7434740:	0x00000000	0x00000000	0x00000000	0x00000000
0xb7434750:	0x00000000	0x00000000	0x00000000	0x00000000
0xb7434760:	0x00000000	0x00000000	0x00000000	0x00000000
0xb7434770:	0x00000000	0x00000000	0x00000000	0x00000000
0xb7434780:	0xbfd9f344	0x00000000	0x00000000	0x00000000
0xb7434790:	0x00000000	0x00000000	0x00000000	0x00000000
0xb74347a0:	0x00000000	0x00000000	0x00000000	0x00000000
0xb74347b0:	0x00000000	0x00000000	0x00000000	0x00000000
tls address: 0xb7434700
stack canary: 0x87354b00
Found a stack address 0xbfd9f344 at 0xb7434780
```  
BTW this is such an OP debugger man, especially the `heap info` part, will it have a chance for you to **modulize** the `heap info` part so everyone can import the module to their own debugger?  
Thanks !

**Comment by scwuaptx** [comment]
Thank you . I use your method to get the tls address. I will modulize the heapinfo in the future.

**Comment by bruce30262** [comment]
No plm :) looking forward to it !
