### ISSUE TITLE
[Bug] heapbase variable is referenced before assignment.

### ISSUE THREAD

**Issue by hama7230** [scwuaptx/Pwngdb#13]
I found a python exception when I tried the `parseheap`.
The error messages are as follows.

```
gdb-peda$ parseheap 
Can't find heap
Python Exception <class 'UnboundLocalError'> local variable 'heapbase' referenced before assignment: 
Python Exception <class 'gdb.error'> Error occurred in Python command: local variable 'heapbase' referenced before assignment: 
Error occurred in Python command: Error occurred in Python command: local variable 'heapbase' referenced before assignment
```

I found the cause of the exception at `parse_heap()` in `angelheap.py`.
When using only main_arena, `main_arena` variable will be correct address in libc and `thread_arena` will be NULL(0).
Therefore no conditional branch is satisfied, the value of `heapbase` is not assignment.

```python
    # if thread_arena == main_arena :
    if main_arena :
        heapbase = int(gdb.execute("x/" + word + " &mp_.sbrk_base",to_string=True).split(":")[1].strip(),16)
    elif thread_arena :
        arena_size = int(gdb.execute("p sizeof(main_arena)",to_string=True).split("=")[1].strip(),16)
        heapbase = thread_arena + arena_size
    else :
        print("Can't find heap")
```
I hope this bug will be fix, thanks.

**Comment by scwuaptx** [comment]
Thanks. 
I add a condition to check if main_arena exists. 
In your case, it would show wrong arena in multithread. 
Thanks again for your report !

**Comment by hama7230** [comment]
I didn't think deeply as you said in multithread. I would like to use the repository you modified.
Thanks to fix the problem !

**Comment by hama7230** [comment]
I didn't think deeply as you said in multithread. I would like to use the repository you modified.
Thanks to fix the problem !
