### ISSUE TITLE
Can not Backtrack to prev state

### ISSUE THREAD

**Issue by TacXingXing** [scwuaptx/Pwngdb#17]
Sorry for Disturbing.
I have a little problem，and i don't know it‘s a bug or not.
My env is Ubuntu 16.04.
I can't come back to prev state We i press "n" for continue,Sometimes I want to view some Information first few steps，But i notice i can't，It looks like:

<img width="857" alt="ubuntu-16 04-ctf 2017-11-13 10-35-16" src="https://user-images.githubusercontent.com/25541720/32707586-e7693d74-c85f-11e7-973d-a79691051b3b.png">

**Comment by scwuaptx** [comment]
Can you give me some test cases ? Let me can reproduce it .
Thanks :)

**Comment by TacXingXing** [comment]
I can not determine it's my termainate profile or not ,when i ssh to my ununtu in item2 of my macos, it Normal
<img width="848" alt="1 tmux tmux 2017-11-13 23-16-49" src="https://user-images.githubusercontent.com/25541720/32732926-ed7edc00-c8c8-11e7-8c16-3cc52e329d6a.png">
But in ubuntu,it really exist
<img width="1034" alt="ubuntu-16 04-ctf 2017-11-13 23-22-57" src="https://user-images.githubusercontent.com/25541720/32733216-a1ce85ca-c8c9-11e7-9796-e45172b06eec.png">
No matter the elf it is，it always exist this problem

**Comment by TacXingXing** [comment]
my env is Ubuntu16.04 Linux ubuntu 4.4.0-98-generic
gdb is GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
python is 2.7.12

**Comment by scwuaptx** [comment]
I think it may be caused by your profile. 
I can't reproduce it in same environment :(

**Comment by TacXingXing** [comment]
Emmm....,Sorry for Disturbing again...I don't think it's caused by my profile..
You know the advantage of gdb is it can view the prev states ,so the problem makes me go crazy.
I try to test in different terminal such as xterm,kconsole,Guake and so on in Ubuntu, but it still have the problem,But it's normal when i ssh to my virtual Ubuntu machine in item2...
Finally i think it's the problem of IO conflict. So i went to see the source code of Peda in your Repositories ,in the near line of number 5245 in the function "context"
<img width="730" alt="ubuntu-16 04-ctf 2017-11-16 01-40-50" src="https://user-images.githubusercontent.com/25541720/32851186-43776a8a-ca6f-11e7-8ab5-75044f6273c5.png">
When i comment `self.clean_screen()`,it works well in all the envirnment!!!
<img width="1295" alt="ubuntu-16 04-ctf 2017-11-16 01-45-16" src="https://user-images.githubusercontent.com/25541720/32851413-d9cec23a-ca6f-11e7-8e79-472fd210ef46.png">
I guess the cause is IO conflict, ssh connection has a little bit delay, so it's has enough to print.
I don't know the intention of this code...Please for explanation thank you...
You peda is really Great，I admire it...

**Comment by scwuaptx** [comment]
I'm sorry for late reply. I think it is my peda issue, so I did not test it with my peda.
Maybe it should be a config for user.
