### ISSUE TITLE
glibc heap analyzing uses a fixed number of fastbins

### ISSUE THREAD

**Issue by eLoopWoo** [scwuaptx/Pwngdb#23]
Analyzing glibc2.24 malloc internals on a 64-bit machine, I'm using both parseheap & heapinfo functionalities.
Basically, heapinfo shows info of 7 fastbins although 10 exist (actually max of actual use is 9?).
```
gdb-peda$ heapinfo
(0x20)     fastbin[0]: 0x555555756060 --> 0x555555756020 --> 0x0
(0x30)     fastbin[1]: 0x0
(0x40)     fastbin[2]: 0x0
(0x50)     fastbin[3]: 0x0
(0x60)     fastbin[4]: 0x0
(0x70)     fastbin[5]: 0x0
(0x80)     fastbin[6]: 0x5555557560a0 --> 0x0
                  top: 0x5555557562e0 (size : 0x20d20) 
       last_remainder: 0x0 (size : 0x0) 
            unsortbin: 0x0
gdb-peda$ p main_arena
$1 = {
  mutex = 0x0, 
  flags = 0x0, 
  fastbinsY = {0x555555756060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5555557560a0, 0x0, 0x5555557561a0, 0x0}, 
  top = 0x5555557562e0, 
```

I found in "mallopt" man page the param M_MXFAST you send to it to change what they describe as
> http://man7.org/linux/man-pages/man3/mallopt.3.html
upper limit for memory allocation requests that are using "fastbins"
The default value is 
`64*sizeof(size_t)/4`
The maximum value is
`80*sizeof(size_t)/4`

Also in the source code, the size of fastbinsY is determined at compile time, by NFASTBINS.
```
//glibc2.24 malloc.c
//https://github.com/bminor/glibc/blob/release/2.24/master/malloc/malloc.c

struct malloc_state
{
  /* Serialize access.  */
  mutex_t mutex;

  /* Flags (formerly in max_fast).  */
  int flags;

  /* Fastbins */
  mfastbinptr fastbinsY[NFASTBINS];

  /* Base of the topmost chunk -- not otherwise kept in a bin */
  mchunkptr top;
```

After a brief check, I saw that in my case NFASTBINS is 10.

Here is the part of the program that modified the max size of chunks in the fastbins (param M_MXFAST).
```
mallopt(M_MXFAST, 0xa0);
void* test = malloc(0x90);
free(test);
```

**Comment by scwuaptx** [comment]
Sorry for late reply.  I am very busy last week :(
I increased the display numbers of fastbin.
