### ISSUE TITLE
a bug of parse_heap

### ISSUE THREAD

**Issue by matrix1001** [scwuaptx/Pwngdb#25]
# Problem

This bug is due to a strange alignment strategy in newer version of 32 bit glibc.

In a nutshell, the first 16 bytes of heap is 0 in glibc-2.26 (32bit), glibc-2.27 (32bit).

As a result, while parsing heap, the first chunk has size 0 and trigger stop.

# Fix

Fix is really easy, just ignore the first chunk if size is 0.

# More

This problem was initially found when I was finishing my project [HeapInspect](https://github.com/matrix1001/heapinspect).

Then I find that `pwndbg` has this problem.  So does your amazing `angelheap`.

![image](https://user-images.githubusercontent.com/32097922/48169779-922a1680-e32f-11e8-8acc-a56fd746ab28.png)

**Comment by scwuaptx** [comment]
Fixed.  Thank you.
