### ISSUE TITLE
do the the command "free"  have bug?

### ISSUE THREAD

**Issue by Byzero512** [scwuaptx/Pwngdb#30]
![image](https://user-images.githubusercontent.com/36794026/53324575-1246ad00-391c-11e9-8a15-9e591cf9efdc.png)

I have fastbin chunk: 0x14fb020, setting its fd and bk truely, and fake small chunk: 0x14fb040,
but not set its element prevsize, so when I free the small chunk, it can not pass the unlink check p->size=next-> prevsize. but use the command " free", it return "True".

**Comment by scwuaptx** [comment]
Thank you for your report. 
I have fixed it. I think it works now.
