### ISSUE TITLE
api "heap" is conflict with gef's heap

### ISSUE THREAD

**Issue by qaqmander** [scwuaptx/Pwngdb#38]
I'm big fan of Pwngdb, at the same time I use gef, but Pwngdb's api 'heap' is conflict with gef's heap, every time I test my docker I need to change Pwngdb's 'heap' to 'heapbase'.
In my opinion, use 'heapbase', 'libcbase' may be better.....

**Comment by scwuaptx** [comment]
Thank you for your suggestion.
I change this command to 'heapbase'.
