### ISSUE TITLE
tcache size error in i386

### ISSUE THREAD

**Issue by JX-Zhang98** [scwuaptx/Pwngdb#41]
The size list of tcache seems architecture-independent, whitch means the size list is still [0x10, 0x20, 0x30,...] in i386 instead of [0x10, 0x18, 0x20,...]. 
look at this:
![error image](http://ww1.sinaimg.cn/large/006z37hrly1g7ukfnmm1cj30if0f1ju9.jpg)

**Comment by JX-Zhang98** [comment]
This error also exits in **heapinfo**

**Comment by JX-Zhang98** [comment]
Also, the chunk align to 16 even if the arch is i386 in glibc 2.27
![](http://ww1.sinaimg.cn/large/006z37hrly1g7um6c1vodj31370ptqcw.jpg)
Maybe, we need to choose different size list according to glibc the binary used.

**Comment by scwuaptx** [comment]
Thank you for your report.
Fixed.
