### ISSUE TITLE
無法在gdb中attach pid

### ISSUE THREAD

**Issue by 0n3t04ll** [scwuaptx/Pwngdb#7]
不好意思，前幾天用了你的pwngdb之後發現無法在gdb裡面attach pid，pidof找到程式的pid後輸入指令at pid 之後顯示No such process...。目前僅能在terminal下sudo gdb -p pid，請問可有解決方式？謝謝

※我的peda是自己另外下載的，不知道有沒有關......
※剛剛沒顯示pid出來><

**Comment by scwuaptx** [comment]
at 會直接去抓你目前 gdb binary 那個 binary 的 process ，attach 則是直接用 pid ，然後看你的情況應該是權限不夠，你要先把 /proc/sys/kernel/yama/ptrace_scope 才能 attach 其他 process

**Comment by 0n3t04ll** [comment]
嗯，我上網看也有說要把ptrace_scope設為0，可是設為0之後也是無法at pid(一樣的訊息：No such process，可是pidof找的到pid)。另外之前不知道ptrace scope的時候我都是sudo gdb開啟後再at pid，不知道這樣是否還有權限問題？

**Comment by L4ys** [comment]
pwngdb 有個指令叫做 "at" ，你要的應該是 "attach" <pid>

**Comment by scwuaptx** [comment]
可以直接打 at ，不過這邊不接 pid ，而是根據你 gdb 所接的 binary 自己去抓相對應的 process

**Comment by 0n3t04ll** [comment]
喔喔瞭解><，謝謝解說
