### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MichaelSmith01** [scwuaptx/Pwngdb#8]
----------error info------------------------------
gdb-peda$ chunkinfo
Can't access memory
gdb-peda$ chunkptr
Python Exception <class 'TypeError'> unsupported operand type(s) for -: 'NoneType' and 'int': 
Python Exception <class 'gdb.error'> Error occurred in Python command: unsupported operand type(s) for -: 'NoneType' and 'int': 
Error occurred in Python command: Error occurred in Python command: unsupported operand type(s) for -: 'NoneType' and 'int'
----------------------------------------
some enviroment
python version 2.7.6
gdb version 7.7
os ubuntu 14.04

**Comment by scwuaptx** [comment]
You need to give parameters (chunk address).
For example : 
gdb-peda$ chunkinfo 0x603000
